hmrc/alert-config-builder

- src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfig.scala
Add a default implementation of environmentConfig in AlertConfig so that
all existing services have a production handler by default, then only
services with handlers in other environments need to be overridden
> TEL-650 default environmentConfig implementation

- src/main/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilderSpec.scala
There was a bug where if a custom command was provided, all environments
were enabled and using that command without being possible to disable
them.
> TEL-650 Allow disabling envs with custom command

- src/main/scala/uk/gov/hmrc/alertconfig/HttpStatusThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/package.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/TeamAlertConfigBuilderSpec.scala
Extend HttpStatusThreshold to allow customisation of alert severity.
This will allow us to raise incidents in PagerDuty at different
severities to allow incidents to be routed differently based on the
severity
> SUP-10538 add severity option to alerts

- .travis.yml
- src/main/scala/uk/gov/hmrc/alertconfig/AlertSeverity.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpStatusThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AllEnvironmentAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/TeamAlertConfigBuilderSpec.scala
Update to use PagerDuty events api v2
Correct the severity names (pagerduty documents them as starting with
a capital letter but only accepts them as lower case!).
Also decided to refactor AlertSeverity class into it's own file as it
doesn't relate specifically to HttpStatusThreshold but other classes can
also use it
Also update travis to use openjdk as oraclejdk8 no longer works on
travis-ci
> SUP-10538 refactor AlertSeverity class

- src/test/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilderSpec.scala
Consistent naming - treat as prefix for consistency.
Added labs version of team-telemetry-heartbeat so
these can be handled too when a test cluster is
stood up.
> TEL-1253 Refactor team-telemetry-test to labs-team-telemetry

- src/main/scala/uk/gov/hmrc/alertconfig/Http5xxThresholdSeverity.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/TeamAlertConfigBuilderSpec.scala
Add new builder to alert-config-builder that allows microservice teams
to create 5xx threshold alerts with custom pagerduty severities
> SUP-10805 add http 5xx threshold with severity

- src/main/scala/uk/gov/hmrc/alertconfig/AlertSeverity.scala
- src/main/scala/uk/gov/hmrc/alertconfig/Http5xxThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpStatusThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/LogMessageThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/ObjectScanner.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfig.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/logging/Logger.scala
- src/main/scala/uk/gov/hmrc/alertconfig/package.scala
- src/test/scala/uk/gov/hmrc/alertconfig/ObjectScannerSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AllEnvironmentAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/TeamAlertConfigBuilderSpec.scala
See SUP-11085 for details.
Due to the use of reflection, No range check is done on the status in the model. The resulting exception was not helpful at all in alert-config. However, a new test will be in alert-config to enforce the correct range of statuses available.
This needs an update in aws-ami-base too:
https://github.com/hmrc/aws-ami-sensu-base/pull/310
> DDCNL-1721: Add generic Int for withHttpStatusThreshold

- .gitignore
- build.sbt
- src/main/scala/uk/gov/hmrc/alertconfig/AlertSeverity.scala
- src/main/scala/uk/gov/hmrc/alertconfig/ExceptionThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/Http5xxThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpAbsolutePercentSplitDownstreamHodThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpAbsolutePercentSplitDownstreamServiceThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpAbsolutePercentSplitThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpMethod.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpStatus.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpStatusPercentThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/HttpStatusThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/MetricsThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/ObjectScanner.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfig.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/logging/Logger.scala
- src/main/scala/uk/gov/hmrc/alertconfig/package.scala
- src/test/scala/uk/gov/hmrc/alertconfig/ObjectScannerSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AllEnvironmentAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/TeamAlertConfigBuilderSpec.scala
--
1. Added new value object for configuring exception threshold alerts to have an overrideable severity
References
--
1. [Spreadsheet of our progress](https://docs.google.com/spreadsheets/d/1bZtS0rAmuZdGZrKQzoe_2FF1iOs1_S8Zm17QUG5t_wk/edit#gid=0)
2. [Flowchart of our plan of action](https://app.diagrams.net/#G1dDuEnL8w3aZonC00vdKzcotRUorsHROE)
3. https://jira.tools.tax.service.gov.uk/browse/TEL-3590
--
Risks
--
1. Me no Scala good
2. Are there other functions that need this treatment?
Next steps
--
1. Update the alert-config repo to use the new version of this library
2. Update the alerts that are to have custom severity
3. Deploy+test
Collaborators
--
1. Co-authored-by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
> TEL-3590 Adds severity to exception threshold alerts

- src/main/scala/uk/gov/hmrc/alertconfig/Http5xxPercentThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builders/TeamAlertConfigBuilderSpec.scala
--
Made 5xx %age thresholds have configurable severity
References
--
1. https://jira.tools.tax.service.gov.uk/browse/TEL-3590
2. https://docs.google.com/spreadsheets/d/1bZtS0rAmuZdGZrKQzoe_2FF1iOs1_S8Zm17QUG5t_wk/edit#gid=0
Evidence of Work
--
Next steps
--
1. Update alert-config repo to set the threshold severity where appropriate
Risks
--
None known
Collaborators
--
Co-authored-by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
> TEL-3590 Adds value object Http5xxPercentThresholdProtocol

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5XXRateIncrease.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
The model inclouds a name field which is not required for dynamic alerts of this sort. But is going to help us during the implementation of the plugin and testing it with different combinations of thresholds.
Based on the outcome of testing different thresholds, we might be able to provide default values for them in follow-up PRs
> TEL-3810 Add config builder for 5xx status rate increase alerts

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertSeverity.scala
- src/main/scala/uk/gov/hmrc/alertconfig/package.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
--
1. Removed any references to `Info` or `Error` severities so that they cannot be used in `alert-config` repo
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-3818
--
* https://build.tax.service.gov.uk/job/PlatOps/job/Libraries/job/alert-config-builder/67
* https://build.tax.service.gov.uk/job/Telemetry/job/alert-config-pr-builder/259
Next Steps
--
1. Merge, get new version number `1.7.0` and update `alert-config` repo
Risks
--
1. Minimal, all the PR checks and tests pass
Collaboration
--
Co-authored-by: Rizina Khatun <66684341+rizinaa99@users.noreply.github.com>
> TEL-3818 First pass at removing INFO and ERROR severities

- build.sbt
- project/build.properties
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusThreshold.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
--
1. Updated Scala/SBT
2. TEL-4145 Permits HttpTrafficThreshold to target an alerting platform
References
--
1. https://jira.tools.tax.service.gov.uk/browse/TEL-4145
--
1. Automated test
Risks
--
None known
Next steps
--
1. Update the alert-config repo to consume this change
Collaborators
--
1. Co-authored by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
> TEL-4145 Permits HttpTrafficThreshold to target an alerting platform

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
--
Following Muhammed's work here https://github.com/hmrc/alert-config-builder/pull/62/files and here https://github.com/hmrc/alert-config-builder/pull/63/files , we are filtering out the non-Sensu alerts from the JSON builder
--
1. automated test
Risks
--
1. Continues to couple alert-config-builder to alert-config
2. continues to have the logic for building Grafana alerts within alert0-config and not here in alert-config-builder where I think perhaps it should be
Next steps
--
Complete the implemetation of this feature in alert-config
Collaborators
--
Co-authored by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
> TEL-4145 Filter out HTTP stats thresholds that do not target Sensu

- README.md
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxPercentThreshold.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- Add alerting platform flag to withHttp5xxPercentThreshold
- Default it to Sensu and cover both Sensu and Grafana scenarios
- Silencing Sensu when another platform is selected. 
-- If using a non-Sensu Alerting platform, just raise the threshold to 333.33%. This way, we can silence Sensu without having to update the existing plugin, which is going to be deprecated soon
> TEL-4197 Add alerting platform flag to withHttp5xxPercentThreshold

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxThreshold.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- Add alerting platform flag to withHttp5xxThreshold
- Default it to Sensu and cover both Sensu and Grafana scenarios
--
Risks
--
None known
Collaborators
--
Co-authored by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
> TEL-4157 Adds alerting platform flag to withHttp5xxThreshold

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ContainerKillThreshold.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
* Adds the ability to set the `alertingPlatform` to the `withContainerKillThreshold` alert
* Makes sure the JSON created by the builder is still a single number as the Sensu plugin expects
* If the alerting platform isn't Sensu then it sets the threshold to `Int.MaxValue` so it doesn't trigger in Sensu
Co-authored-by: Rob White <Crumplepang@users.noreply.github.com>
> TEL-4154 Add alertingPlatform flag for withContainerKillThreshold

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ErrorsLoggedThreshold.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
--
1. Created class for ErrorsLoggedThreshold and added alertingPlatform parameter
2. Updated sensu config builder to disable errors logged threshold alert when the alertingPlatform is Grafana by setting threshold to Int.MaxValue
3. Added test to prove that withErrorsLoggedThreshold is disabled in Sensu when alertingPlatform is Grafana
4. Refactored test names to be consistent with each other
5. Removed test which has been ignored since 2016 and doesn't work
6. Added TeamAlertBuilder tests for container kills
> TEL-4192 Add alertingPlatform flag for withErrorsLoggedThreshold

- .github/pull_request_template.md
- project/LibDependencies.scala
- project/plugins.sbt
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Config.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YAMLAlerts.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlBuilderSpec.scala
--
1. Added Scala for YAML builder
2. Added Github template
3. Adds bare-bones unit test for YAMLBuilder
4. Updated auto builder package
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4265
--
compiles
Next Steps
--
1. Consume this YAML class from alert-config
Risks
--
1. Unit test doesn't do a lot... better than nothing though
2. I'm hoping that it writes to the correct `target` directory when consumed as a library from `alert-config` - will have to see. Haven't tested with that yet, - **is there a way to test a different `alert-config-builder` lib version with `alert-config`?**
Collaboration
--
Co-authored by: Ali Bahman <abn@webit4.me>
> TEL-4265 Moves YAML builder from alert-config

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentVars.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
1. Set alertingPlatform to Default for withAverageCPUThreshold for TeamAlertConfigBuilder (previous PR only set it in AlertConfigBuilder)
2. Added tests which would have caught the above mistake
3. Added tests for YAML config
4. Do not add AverageCPUThreshold to YAML if the threshold is set to Int.MaxValue (e.g. disabled)
5. rename unSetEnv to unsetEnv
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4323
--
1. Passing tests
Next Steps
--
1. Update alert-config and migrate averageCPUThreshold alert in integration from sensu to grafana
> TEL-4323 ensure default platform is set in both AlertConfigBuilder and TeamAlertConfigBuilder

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ContainerKillThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ErrorsLoggedThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ExceptionThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxPercentThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusPercentThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpTrafficThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/LogMessageThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/MetricsThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/TotalHttpRequestThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlBuilderSpec.scala
--
1. Migrated all alerts in integration to Grafana
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4323
--
1. Added tests, all tests passing
2. Tested locally with alert-config
Next Steps
--
1. Update alert-config to do the actual migration
> TEL-4323 migrate all alerts in integration to grafana

- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
--
1. Add management environment to migration "spreadsheet" (even though we don't use it for standard alerts). The absence of this environment is causing alert-config deploy job to fail. Microservice alerts cannot be created in management as we don't have any alert-config so this is a no-op
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4343
--
1. Built library from branch, updated version in alert-config and deploy to management from branch, which succeeded:
Next Steps
--
1. Update alert-config to use the new release of alert-config-builder (which will automatically be created by jenkins after this PR is merged)
Risks
--
1. Adding management to "the spreadsheet" could potentially confuse future engineers into thinking management is part of …
> TEL-4343 add management environment to migration (even though we don't use it for standard alerts)

- .tool-versions
- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4349
--
n/a
Next Steps
--
1. Update alert-config to use new version of alert-config-builder
Risks
--
1. "To check this has worked effectively, find a service which has this alert configured and validate that it appears in https://grafana-alerting.mdtp-production.telemetry.tax.service.gov.uk/alerting/list and does not appear in the ElasticSearch PagerDuty mappings (instructions here: https://github.com/hmrc/telemetry/blob/main/snippets/elasticsearch.md#fetch-for-a-given-service)." it's not yet clear to me what this is all about
> TEL-4349 migrate users to Grafana alerting in production: TotalHttpRequestThreshold

- project/plugins.sbt
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Integrations.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlWriter.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
Added functionality to create a YAML file that contains all the PagerDuty integrations active for that environment along with what severities are enabled for that handler in that environment
<details>
<summary>Example output file (click to expand)</summary>
```yaml
integrations:
- name: "labs-team-telemetry"
severitiesEnabled:
warning: true
critical: true
- name: "build-and-deploy-warnings"
severitiesEnabled:
warning: true
critical: true
- name: "cip-asad-nonprod"
severitiesEnabled:
warning: false
critical: true
- name: "cip-attrep-nonprod"
severitiesEnabled:
warning: true
critical: true
- name: "cip-cdp-nonprod"
severitiesEnabled:
warning: false
critical: true
- name: "cip-cit-nonprod"
severitiesEnabled:
warning: false
critical: true
- name: "cip-dbd-nonprod"
severitiesEnabled:
warning: …
```
> TEL-4363 Integrations yaml

- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http90PercentileThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Config.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlAlerts.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
--
1. Added support for `Http90PercentileResponseTimeThreshold` as a Grafana alert
2. Defaulted it to Grafana in mdtp-integration only
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4331
--
1. Autoamted tests
2. Configured `alert-config` locally to use this branch; it outputs the following for alert-simulator in integration:
```
http90PercentileResponseTimeThreshold:
- timePeriod: 14
count: 1000
severity: "warning"
- timePeriod: 14
count: 2000
severity: "critical"
```
Next Steps
--
1. Update alert-config
2. 2. Implement in telemetry-grafana-alert-config
3. If this is all OK, enable `Http90PercentileResponseTimeThreshold` for other envs in `src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala`
Risks
--
1. good chance I've …
> TEL-4331 Adds support for Http90PercentileResponseTimeThreshold as a Grafana alert

- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Integrations.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlWriter.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilderSpec.scala
Generate YAML severities as an array to make processing easier in `telemetry-grafana-alert-config`
```yaml
integrations:
- name: agent-services
severitiesEnabled:
- warning
- critical
- name: alcohol-duty-reform
severitiesEnabled:
- warning
- critical
```
> TEL-4363 Generate integrations YAML as array

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertSeverity.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Integrations.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AllEnvironmentAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilderSpec.scala
--
1. Added info as a valid status
The idea is that we can change the flip-flop metric so that it create an `info` alert instead of a critical one. This is semantically better - having big red scary alerts in Pagerduty is a problem on support.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4399
--
Next Steps
--
1. Update alert-config to support this for the `alert-simulator` to send `info` level alarms.
Risks
--
1. I might have misunderstood the new severity mechanism
Collaboration
--
> TEL-4399 Adds info as valid status for AlertConfig alert

- src/main/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4408
See https://github.com/hmrc/alert-config-builder/pull/95 for full details
--
1. This worked just fine in integration
2. Integration stopped spamming #team-telemetry-tests
Next Steps
--
1. See if there's a way we can figure out how to set urgency to LOW
Risks
--
1.
Collaboration
--
Co-authored by: Rob White <Crumplepang@users.noreply.github.com>
> TEL-4408 Enables info alert level everywhere

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AppConfigValidator.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
- In order to ensure that we don't trigger alerts for services that aren't actually deployed (no data can cause false positives), there was some existing business logic which only created service-config if that service has an entry in app-config-$env. This ensured that the $service.json config file was not created for these undeployed services. 
- However, this logic only applied to alerts created in Sensu. This is because we generate YAML (which is used by Grafana-Alerting) based on the pre-filtered Scala objects in memory - not based on the created json files.
- This PR replicates that logic for the generation of Grafana-Alerting YAML.
- Note - rather than duplicate the exact same logic in two places, I moved the logic to a helper object. 
References
-- …
> TEL-4397 Only create alert config for services that are deployed

- src/test/scala/uk/gov/hmrc/alertconfig/builder/ObjectScannerSpec.scala
This is just a tweak to test the alert-config-builder pipeline will run Java 21 and NOT Java 11
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4389
--
1. `sbt clean test` no longer emits a warning
2. Build is using right Java: ![image](https://github.com/hmrc/alert-config-builder/assets/205245/108d390c-0e4c-4851-bafe-0dcb13d9537c)
Risks
--
None
Collaboration
--
> TEL-4389 Resolves warning for multiarg infix syntax

- project/plugins.sbt
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpAbsolutePercentSplitThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Config.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlAlerts.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
1. We now generate yaml for the HttpAbsolutePercentSplitThreshold alerts
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4438
--
1. 
2. 
Next Steps
--
1. Merge
2. Check that the Alert-Simulator config exists in the S3 bucket as it rolls out through the environments
Risks
--
1. ?
Collaboration
--
Co-authored-by: Muhammed Ahmed [ma3574@users.noreply.github.com](mailto:ma3574@users.noreply.github.com)
> TEL-4438 Generate yaml for HttpAbsolutePercentSplitThreshold alerts

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxPercentThreshold.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala
--
1. Added an option 5xx count baseline to the 5xxPercentageThreshold.
2. This defaults to 1 which will tell `telemetry-grafana-alert-config` to in effect ignore it.
3. This means that the alert can be the same in every case - it will always have a minimum count threshold
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4446
--
Next Steps
--
1. Update `alert-config` to support this modified DSL and output the new parameter in Yaml
2. Update `telemetry-grafana-alert-config` to support this parameter and test on a lab <== this is the tricky bit
Risks
--
1. Are the changes I have made to the DSL acceptable?
3. Is it clear that this parameter is optional?
4. Is there a better way to do this?
Collaboration
-- …
> TEL-4446 Adds optional 5xx count baseline to 5xxPercentThreshold alarm

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertSeverity.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertingPlatform.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AverageCPUThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ContainerKillThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ExceptionThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxPercentThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http90PercentileThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusPercentThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpTrafficThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/LogMessageThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/MetricsThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/TotalHttpRequestThreshold.scala
--
1. Added Scaladoc annotations
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4470
--
1. `sbt doc` generates viable docs
Next Steps
--
1. Update alert-config to use the newest version
2. **Assert that** alert-config in IDE offers intellisense-like help
Risks
--
1. We now have the documentation in 2 places: alert-config README and in the source code
> TEL-4470 Adds Scaladoc annotations

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfig.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AllEnvironmentAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
1. In order to replace the outdated Sensu 'handler' term with 'Integration' in alert-config, we needed to make changes to the models themselves in the alert-config-builder.
This PR replaces the word handler with Integration, whereever it is appropriate. 
**Exceptions (Where I have left the term 'handler' for now)**:
- Where we actually generate the json
- Where we create the expected json object in the EnvironmentAlertBuilder
- Where we define the actual command ran by Sensu:
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4469
--
Published this locally, and updated alert-config using it. All tests passed.
Next Steps
--
1. merge this
2. Make a copy of the various alert config artefacts locally
3. Merge my follow-on alert-config PR
4. …
> TEL-4469 Replace handler with integrations where appropriate

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlert.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfig.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilderSpec.scala
--
1. Extended custom alerts, to also allow overriding of environment config. 
2. Remove unused parameter from IntegrationsYamlBuilder.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4504
--
1. N/A
Next Steps
--
1. Build and roll out to alert-config
Risks
--
1. ?
Collaboration
--
Co-authored-by: Gavin Davies [gavD@users.noreply.github.com](mailto:gavD@users.noreply.github.com)
> TEL-4504 Extend custom-alerts to allow overriding of environment config

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpAbsolutePercentSplitDownstreamHodThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Config.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlAlerts.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
Adds YAML/Grafana export for HttpAbsolutePercentSplitDownstreamHodThreshold alerts
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
> TEL-4535 Add HttpAbsolutePercentSplitDownstreamHodThreshold for Grafana

- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
--
1. This was the missing piece of the puzzle that caused the heartbeat alerts to go off, as detailed in [TEL-4569](https://jira.tools.tax.service.gov.uk/browse/TEL-4569)
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4504
--
1. I tested that this fixes the heartbeat issue, and it does - see notes on TEL-4569. 
Next Steps
--
1. Build this, and then bump alert-config. Ensuring that it is in the same PR as the Alert-Config custom alert changes.
Risks
--
1. Another, unrelated issue presents itself. I plan to mitigate this by deploying Alert-Config off a branch, as well as the Terraform, in order to test alerts still fire as expected, and allow easier rollback.
> TEL-4504 Update heartbeat handler integration name

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomCloudWatchMetricAlert.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/Statistic.scala
--
1. Noted that this was hard coded in Cloudwatch alerts. We don't want that.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4554
--
n/a
Next Steps
--
1. Update alert-config to use this new feature
2. Update telemetry-grafana-alert-config to use this new feature
Risks
--
1. None known, but ideally should have tests
Collaboration
--
Co-authored by: Ali Bahman <abn@webit4.me>
> TEL-4554 Adds support for 'statistic' to Cloudwatch alerts

- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
--
1. Migrate **Http5xxThreshold** to **Grafana** in **mdtp-production**
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4558
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
> TEL-4558 Migrate Http5xxThreshold to Grafana in mdtp-production

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpAbsolutePercentSplitDownstreamServiceThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Config.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlAlerts.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
--
1. Copied what was done in https://github.com/hmrc/alert-config-builder/pull/129
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4602
--
Next Steps
--
1. Copy what was done in https://github.com/hmrc/alert-config/pull/3541/files
Risks
--
None known
Collaboration
--
> TEL-4602 Adds Grafana support for withHttpAbsolutePercentSplitDownstreamHodThreshold

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CheckIntervalMinutes.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomElasticsearchAlert.scala
* Added ability to use specific check intervals from a constant to limit options
```
"interval": 60, // 1 Min
"interval": 120, // 2 Min
"interval": 150, // 2.5 Min
"interval": 180, // 3 Min
"interval": 300, // 5 Min
"interval": 600, // 10 Min
"interval": 900, // 15 min 
"interval": 1800, // 30 min
"interval": 28800 // 8 hours
```
Replicated all the above except 2.5 min as that's just weird. It's used by one alert and it's a Telemetry alert so we'll just refactor it. 
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
> TEL-4585 - Add specific check intervals

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CheckIntervalMinutes.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/TimeRangeAsMinutes.scala
--
1. Add NINETY_MINUTES to both TimeRangeAsMinutes and CheckIntervalMinutes constants 
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4617
--
1. Code is as described, NINETY_MINUTES is available for check definitions in alert-config
Next Steps
--
1. Roll out and use
Collaboration
--
> TEL-4617 Add 90 minutes for check interval and time range queries

- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4557
--
Next Steps
--
1. Update alert-config to new version
2. Observe rollout
Risks
--
1. This will put several thousand additional alerts onto Grafana-alerting via Elasticsearch
> TEL-4557 Migrates ExceptionThreshold alert to Grafana in prod

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomCloudWatchMetricAlert.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomElasticsearchAlert.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomGraphiteMetricAlert.scala
--
In CustomGraphiteMetricAlert we have the following parameter: evaluationPeriodMinutes
Then in terraform we set the time range using that value
So in grafana land, the terms ‘evaluation interval’ and ‘evaluation group’ refers to how often the check runs
Whereas time_range refers to the time range over which the query will evaluate data.
We have changed `evaluationPeriodMinutes` to `queryTimeRangeMinutes`, so that our terminology better matches that of the Grafana docs.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4712
--
1. Tested it with alert-config using sbt buildLocal
Next Steps
--
1. Once built, update alert-config to use new builder, and update param names.
2. Update param names in telemetry-grafana-alert-config
Risks
--
1. I miss …
> TEL-4712 Improving naming of parameter

- src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
1. Put Http5xxPercentThreshold live on grafana-alerting
2. Updated tests
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4529
--
Next Steps
--
1. Update alert-config
2. Observe rollout
3. Announce
Risks
--
None known
Collaboration
--
Co-authored by: Ali Bahman <abn@webit4.me>
Co-authored-by: Damon Wright
> TEL-4529 Puts Http5xxPercentThreshold live on grafana-alerting

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CheckIntervalMinutes.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomGraphiteMetricAlert.scala
--
1. Add checkIntervalMinutes same as Elasticsearch metrics alerts have, so that we can manipulate the evaluation interval for graphite alerts.
--
Co-Authored-By: @ma3574
> TEL-4699 add checkIntervalMinutes to custom graphite metrics alerts

- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
--
1. Changed the discovery of severities to only include ones that the integration supports
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4686
--
1. Before
```
- service: p800-refunds-frontend
alerts:
...
httpTrafficThresholds:
- count: 50
maxMinutesBelowThreshold: 5
severity: warning
- count: 10
maxMinutesBelowThreshold: 5
severity: critical
http90PercentileResponseTimeThreshold:
- timePeriod: 15
count: 1000
severity: warning
- timePeriod: 15
count: 2500
severity: critical
pagerduty:
- integrationKeyName: payments
- integrationKeyName: payments-oceans-8
```
3. After
```
- service: p800-refunds-frontend
alerts:
...
httpTrafficThresholds:
- count: 10
maxMinutesBelowThreshold: 5
severity: critical
http90PercentileResponseTimeThreshold:
- …
```
> Only flatten severities for current integration

- README.md
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfig.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AllEnvironmentAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilderSpec.scala
--
1. Ensured you have to explicitly enable production
2. Adds documentation for local testing of `alert-config-builder` + `alert-config` changes
3. Forces overriding of `AlertConfig.environmentConfig` so that if you don't specify and envs, it will crash
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4722
--
1. Gimmicked local `alert-config` to use this branch
2. Generated services.yml locally with old and new versions of alert-config-builder
3. **Asserted that** where no environment config was present, the builder crashed:
```
[error] /Users/gavin/Code/telemetry/alert-config/src/main/scala/uk/gov/hmrc/alertconfig/configs/DASSSDLTFiling.scala:11:8: object creation impossible.
[error] Missing implementation for member of trait AlertConfig: …
```
> TEL-4722 Ensures users have to explicitly enable production

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomHttpEndpointAlert.scala
* Added `runbookUrl` field for `CustomHttpEndpointAlert` types
* Changed `expectedQueryString` -> `expectedStringInResponse` for clarity
* 
Co-authored-by: Alex Tasioulis @alextcap <alextcap@users.noreply.github.com>
> TEL-4663 Modify HTTP Endpoint type

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/TimeRangeAsMinutes.scala
--
1. Add THREE_MINUTES option for TimeRangeAsMinutes 
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4763
> add THREE_MINUTES option for TimeRangeAsMinutes

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomElasticsearchAlert.scala
--
1. update CustomElasticsearchAlert to match behaviour of CustomGraphiteMetricAlert - checkIntervalMinutes should default to 2 minutes as almost all checks will use this behaviour
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4744
> TEL-4744 make checkIntervalMinutes consistent

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
--
1. Removed management from the list of all environments, as nothing gets deployed to management and in sensu we have almost no alerts in management
2. Created a new list of environments which we can use for those telemetry checks which are deployed in all environments including management
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4771
--
1. YOLO
Next Steps
--
1. Update already migrated custom alerts which need to be run in management to use the new forAllEnvironmentsPlusManagement
Risks
--
1. We accidentally disable an alert which is needed in management
> TEL-4771 remove management from the list of all environments

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
--
1. Changed EnvironmentThresholds from Option[Int] to Option[Long]. I did this because here https://github.com/hmrc/aws-ami-telemetry-sensu/blob/35410a6bdb15027eb405eb7b1d52e4eb8bc447a5/files/sensu/conf.d/checks/ddcops_deskpro_rds_free_memory.json#L4C150-L4C160 I need to use a big number and it doesn't fit in Int 😭 
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4784
Next Steps
--
1. Check what happens with alert-config
Risks
--
1. A bunch of stuff breaks because it doesn't like the new type and we need to update type in a bunch of places
Collaboration
--
Co-authored-by: @gavD
> change EnvironmentThresholds from Option[Int] to Option[Long]

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CheckIntervalMinutes.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomCloudWatchMetricAlert.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomElasticsearchAlert.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/Statistic.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/TimeRangeAsMinutes.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlAlerts.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlWriter.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/AllEnvironmentAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
--
1. scala fmt all & fix issue with yaml output showing e.g. "value: 9" instead of "9" after latest merge
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4784
Next Steps
--
1. Test the yaml is correct... not sure how to generate the yaml locally :/ 
Risks
--
1. Yaml is still not correct
Collaboration
--
Co-authored-by: @gavD
> TEL-4784 scala fmt all & fix issue with yaml output showing e.g. "value: 9" instead of "9" after latest merge

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfig.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/AverageCPUThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ContainerKillThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ErrorsLoggedThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/ExceptionThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxPercentThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/TotalHttpRequestThreshold.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala
--
1. Improve the way that we disable alerts, by making each alert type `Option[x] = None` rather than `x=Int.MaxValue`
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4770
--
1. Tests passing
2. Built library from branch and tested locally, with some changes in alert-config we end up with the exact same config
Next Steps
--
1. Will probably need to update any alert-configs which pass in thresholds using the constructor rather than the `.withThreshold` builder pattern. This has the added bonus of making alert-config more consistent
Risks
--
1. We accidentally enable alerts which have been disabled in unexpected ways
> TEL-4770 improve method of disabling alerts

- src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
--
1. Made validation fail only if Http5xxPercentThreshold is set to OVER 100% (100% itself is valid)
2. Copied validation for Http90PercentileResponseTimeThreshold from TeamAlertConfigBuilder to AlertConfigBuilder so that the functionality is identical
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4770
--
1. Passing tests
> TEL-4770 fix Http5xxPercentThreshold validation to support 100%

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomGraphiteMetricAlert.scala
--
1. Add alertPerInstance parameter to custom graphite alerts to replicate the functionality of [check_graphite_wildcard](https://github.com/hmrc/aws-ami-telemetry-sensu/blob/main/files/sensu/plugins/check-graphite-wildcard.rb) sensu plugin
2. Sorted parameters for some reason that I need healing from!
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4805
--
1. Tested by building from branch and using in alert-config and telemetry-grafana-alert-config
Next Steps
--
1. Update library version in alert-config and deploy example/test using telemetry-grafana-alert-config
> TEL-4805 allow generating multiple alerts (per instance) from graphite checks

- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfigYamlBuilder.scala
- src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomElasticsearchPercentageSplitAlert.scala
--
1. Add new custom alert type for alerting on either a percentage of a subset of logs (when total logs is above 'split' threshold), or an absolute threshold (when total logs is below 'split' threshold)
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4802
--
1. Tested from branch:
Alerts on absolute threshold when total records is <= split threshold:
Alerts on percentage threshold when total records is > split threshold:
Next Steps
--
1. Add alert in alert-config
2. Add new terraform module
Collaboration
--
> TEL-4802 add custom alert type for percentage split alert based on logs
