src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builders/TeamAlertConfigBuilderSpec.scala
In an attempt to make clearer to library users
=> TEL-750 Rename method used on builder

src/main/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builders/EnvironmentAlertBuilderSpec.scala
Add option for team to be able to customise a sensu handler with a
different command
=> TEL-650 add option to customise handler command

README.md, src/main/scala/uk/gov/hmrc/alertconfig/MetricsThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builders/AlertConfigBuilderSpec.scala
Co-authored-by: Rob White <Crumplepang@users.noreply.github.com>
=> TEL-3110 Add Metrics threshold with basic test

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/LogMessageThreshold.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
Co-authored-by: Rob White <Crumplepang@users.noreply.github.com>
=> TEL-3722 - Add severity to withLogMessageThreshold

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusFloorThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpTrafficThreshold.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
Co-authored-by: Timothy Fothergill <67912934+TimothyFothergill@users.noreply.github.com>
Co-authored-by: Gavin Davies <gavD@users.noreply.github.com>
=> TEL-3672 - New HttpTrafficThreshold added

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
=> TEL-3672 throw exception if withHttpTrafficThreshold is duplicated by a given microservice

src/test/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilderSpec.scala
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
=> TEL-1255 - Remove dose reference

project/plugins.sbt, src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/Http90PercentileThreshold.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
Co-authored-by: Ali Bahman <1422984+webit4me@users.noreply.github.com>
=> TEL-3937 Add timePeriod config to withHttp90PercentileResponseTimeThreshold

.scalafmt.conf, .tool-versions, README.md, project/plugins.sbt, src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfig.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertSeverity.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertingPlatform.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/ExceptionThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5XXRateIncrease.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxPercentThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/Http5xxThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/Http90PercentileThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpAbsolutePercentSplitDownstreamHodThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpAbsolutePercentSplitDownstreamServiceThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpAbsolutePercentSplitThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusPercentThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpStatusThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpTrafficThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/LogMessageThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/MetricsThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/ObjectScanner.scala, src/main/scala/uk/gov/hmrc/alertconfig/package.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AllEnvironmentAlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/ObjectScannerSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- Add scalafmt
- Update document
- Add tools version
=> TEL-4197 Formatting

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/ExceptionThreshold.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala
- Add alerting platform flag to withExceptionThreshold
- Default it to Sensu and cover both Sensu and Grafana scenarios
--
Risks
--
None known
Collaborators
--
Co-authored by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
=> TEL-4191 Adds alerting platform flag to withExceptionThreshold

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
Co-authored-by: Rob White <Crumplepang@users.noreply.github.com>
=> TEL-4324 Migrate standard alerts to Grafana in Development

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
Co-authored-by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
=> TEL-4347 Enable Grafana Alerting in Staging

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
=> TEL-4348 migrate externaltest alerts to Grafana

src/main/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/EnvironmentAlertBuilderSpec.scala
--
1. We tried this "properly" before, but Sensu crashes HARD (see TEL-4404)
2. This change means the info status will be added only for:
a. the "team-telemetry-heartbeat" handler
b. in YAML (for Grafana)
3. Prevented any other way of adding the Info status in the `severitiesFor` function
**Blast radius** is as SMALL as possible - Grafana Integration ONLY. So it can't (theoretically!) knock over Sensu again.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4408
--
1. Automated tests ✅ 
2. Tested bhy publishing and importing to alert-config locally; here is the config it generates:
integration Sensu unaffected: ✅ 
```
[success] Total time: 1 s, completed 29 Feb 2024, 16:24:55
"team-telemetry-heartbeat": {
"command": …
```
=> TEL-4408 Enables info for team-telemetry-heartbeat handler in Grafana ONLY in Integration ONLY

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfig.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomLogAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomMetricAlert.scala
Co-authored-by: Gavin Davies <gavD@users.noreply.github.com>
=> TEL-4338 Add extra properties for custom alerts

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomMetricAlert.scala
Co-authored-by: Gavin Davies <gavD@users.noreply.github.com>
=> TEL-4338 Change url to uri

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomMetricAlert.scala
Co-authored-by: Gavin Davies <gavD@users.noreply.github.com>
=> TEL-4338 Dashboards panel id

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
=> TEL-4338 set externalTest to be externaltest

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfig.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomLogAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomMetricAlert.scala
=> TEL-4338 Remove unused field and rename ruleGroupName for clarity

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomMetricAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/ReducerFunction.scala
--
1. Add optional parameter to define reducer function, only for custom metric alerts
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4514
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4514 Add optional parameter to define reducer function

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4446
=> TEL-4446 Adds note on go-live for Http5xxPercentThreshold

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala
Fixes a missing piece of docs
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4470
=> TEL-4470 Tidies up Scaladoc

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CloudWatchSource.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfigYamlBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomCloudWatchMetricAlert.scala
Needs to be merged before https://github.com/hmrc/alert-config/pull/3486
=> TEL-4527 Add custom-alerts DSL for CloudWatch based alerts

src/main/scala/uk/gov/hmrc/alertconfig/builder/AverageCPUThreshold.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
--
1. Add companion object to set the same threshold for all envinments
2. Remove unnecessary comments, which were causing issues with local publishing
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4450
--
works on my machine :smile_cat: 
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4450 Add companion object to set the same threshold for all envs

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4436
--
n/a
Risks
--
1. Moving fast
a. This is endorsed by Saskia
b. we understand and accept the risk of moving more quickly, in return for not falling for the Stooges effect
c. If we don't do this, we end up with the 3 stooges door problem
2. Test updates are an absolute faff
Next Steps
--
1. Update alert-config
2. Observe rollout
3. Check for any degradation in performance
=> TEL-4436/TEL-4437/TEL-4532/TEL-4434 Migrates prod alerts

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
--
1.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4450
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4450 Correct typo

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4435
=> TEL-4435 Migrates withAverageCPUThreshold to Grafana Alerting in prod

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfigYamlBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomGraphiteMetricAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala
--
1. Rename CustomMetricAlert to CustomGraphiteMetricAlert
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4549
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4549 Rename CustomMetricAlert to CustomGraphiteMetricAlert

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfigYamlBuilder.scala
--
1. correct plural naming
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4549
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4549 correct plural naming

project/build.properties, project/plugins.sbt
Dependabot told us about old deps. This should update them.
=> BAU: Updates dependencies

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/IntegrationsYamlBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4561
--
Next Steps
--
1. Observe rollout
2. Scale infrastructure accordingly if load increases
Risks
--
1. Increased load on `carbonapi-alerting`/`clickhouse`
Collaboration
--
Co-authored by: Rob White <Crumplepang@users.noreply.github.com>
=> TEL-4561 Migrates log-message-thresholds to production

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfigYamlBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomElasticsearchAlert.scala
Adds new type for custom-alerts: `CustomElasticsearchAlert`
=> TEL-4585 Add elasticsearch custom alerts

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
1. Rename `totalHttpRequestsCountThreshold` to `totalHttpRequestThreshold`
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4556
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4556 Rename TotalHttpRequestsCountThreshold to totalHttpRequestThreshold

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomCloudWatchMetricAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomElasticsearchAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomGraphiteMetricAlert.scala
=> TEL-4604 Improve reducerFunction docs

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CheckIntervalMinutes.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/TimeRangeAsMinutes.scala
--
1. Add 4 mins range and interval to simulate Sensu 2 occurrences in 2 mins intervals
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4633
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4633 Add 4 mins range and interval

src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/TeamAlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4560
--
Next Steps
--
1. Update alert-config repo accordingly
Risks
--
1. Load on production
a. We will check our dashboards post-deploy
=> TEL-4560 Switches HttpStatusThreshold to grafana in prod

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
1. Removed withMetricsThreshold
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4628
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4628 Remove withMetricsThreshold

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/GrafanaMigration.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/HttpEndpointAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Config.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlAlerts.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/MigrationTests.scala
--
1. Add withHttpEndpointAlert
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4661
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
Co-authored-by: @jonnydh
=> TEL-4661 Add withHttpEndpointAlert

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomGraphiteMetricAlert.scala
--
1.
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-
--
1.
Next Steps
--
1.
Risks
--
1.
Collaboration
--
=> TEL-4699 set default None value for pendingPeriodMinutes

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfigYamlBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlWriter.scala
Co-authored-by: Alex Tasioulis @alextcap <alex.tasioulis@capgemini.com>
=> TEL-4735 Remove alerts that have integrations disabled in a given environment

src/main/scala/uk/gov/hmrc/alertconfig/builder/AlertConfigBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomAlertConfigYamlBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomHttpEndpointAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentsEnabled.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/HttpEndpointAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilder.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/Config.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/yaml/YamlWriter.scala, src/test/scala/uk/gov/hmrc/alertconfig/builder/yaml/AlertsYamlBuilderSpec.scala
Co-authored-by: Damon Wright @wrightda101 <150913287+wrightda101@users.noreply.github.com>
=>  TEL-4745 Move HttpEndpointAlerts from standard-alerts to custom-alerts

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomGraphiteMetricAlert.scala, src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/CustomHttpEndpointAlert.scala
Co-authored-by: Gavin Davies @gavD <gavD@users.noreply.github.com>
Co-authored-by: Alex Tasioulis @alextcap <alextcap@users.noreply.github.com>
=> TEL-4663 Additional fields for CustomHttpEndpointAlert

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
--
1. change other definitions related to EnvironmentThresholds from Int to Long
References
--
https://jira.tools.tax.service.gov.uk/browse/TEL-4784
Next Steps
--
1. Check alert-config works (cannot get the local build to work correctly 😢 )
Risks
--
1. Need more PRs
Collaboration
--
Co-authored-by: @gavD
=> change other definitions related to EnvironmentThresholds from Int to Long

src/main/scala/uk/gov/hmrc/alertconfig/builder/custom/EnvironmentThresholds.scala
Co-authored-by: Alex Tasioulis @alextcap <alextcap@users.noreply.github.com>
=> TEL-4784 Accept any Number type for threshold
